import { CSSProperties } from "react";
import { ACCENT } from "@/constants/inbox";

const styles: Record<string, CSSProperties> = {
  app: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    fontFamily: "system-ui, -apple-system, sans-serif",
    background: "#fff",
    color: "#1a1a1a",
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 20px",
    borderBottom: "1px solid #e5e5e5",
  },
  logo: { display: "flex", alignItems: "center", gap: 8 },
  logoIcon: {
    width: 28,
    height: 28,
    background: ACCENT,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontSize: 14,
  },
  logoText: { fontWeight: 600, fontSize: 16 },
  searchInput: {
    border: "1px solid #ddd",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 13,
    width: 220,
    outline: "none",
  },
  btnOutline: {
    padding: "6px 14px",
    border: "1px solid #ddd",
    borderRadius: 8,
    background: "transparent",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 500,
  },
  main: { display: "flex", flex: 1, overflow: "hidden" },
  sidebar: {
    width: 230,
    borderRight: "1px solid #e5e5e5",
    overflowY: "auto",
    flexShrink: 0,
  },
  sidebarHeader: {
    padding: "12px 16px 6px",
    fontSize: 11,
    fontWeight: 600,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    margin: 0,
  },
  convoItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 16px",
    cursor: "pointer",
    borderLeft: "2px solid transparent",
    transition: "background 0.1s",
  },
  convoItemActive: {
    background: "#f5f3ff",
    borderLeftColor: ACCENT,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  },
  convoInfo: { flex: 1, minWidth: 0 },
  convoName: {
    fontSize: 13,
    fontWeight: 600,
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  convoPreview: {
    fontSize: 12,
    color: "#888",
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  badge: {
    background: ACCENT,
    color: "white",
    borderRadius: 99,
    fontSize: 10,
    padding: "2px 6px",
    fontWeight: 600,
    flexShrink: 0,
  },
  readingPane: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  msgHeader: { padding: "16px 20px 12px", borderBottom: "1px solid #e5e5e5" },
  msgSubject: { fontSize: 17, fontWeight: 600, margin: "0 0 8px" },
  msgMeta: { display: "flex", alignItems: "center", gap: 10 },
  senderAvatar: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "#EEEDFE",
    color: "#3C3489",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 600,
  },
  msgFrom: { fontSize: 13, color: "#555" },
  msgTime: { fontSize: 12, color: "#999", marginLeft: "auto" },
  msgBody: {
    flex: 1,
    padding: "16px 20px",
    overflowY: "auto",
    fontSize: 14,
    color: "#444",
    lineHeight: 1.7,
  },
  replyArea: { padding: "12px 20px 16px", borderTop: "1px solid #e5e5e5" },
  replyTextarea: {
    width: "100%",
    border: "1px solid #ddd",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 13,
    fontFamily: "inherit",
    resize: "none",
    outline: "none",
    boxSizing: "border-box",
  },
  replyFooter: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 12,
    marginTop: 8,
  },
  btnSend: {
    padding: "7px 18px",
    background: ACCENT,
    color: "white",
    border: "none",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  loginCard: {
    background: "white",
    borderRadius: 16,
    padding: "32px 36px",
    width: 340,
    boxShadow: "0 8px 32px rgba(0,0,0,0.12)",
  },
  loginTitle: { fontSize: 22, fontWeight: 700, margin: "0 0 4px" },
  loginSub: { fontSize: 14, color: "#666", margin: "0 0 20px" },
  field: { marginBottom: 14 },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#555",
    marginBottom: 5,
  },
  input: {
    width: "100%",
    border: "1px solid #ddd",
    borderRadius: 8,
    padding: "8px 12px",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    color: "#1a1a1a",
    background: "#ffffff",
  },
  errorText: { fontSize: 13, color: "#c0392b", margin: "0 0 12px" },
  btnPrimary: {
    width: "100%",
    padding: "10px",
    background: ACCENT,
    color: "white",
    border: "none",
    borderRadius: 8,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
};

export default styles;